### ISSUE TITLE
redundant calculation

### ISSUE THREAD

**Issue by jingsam** [mapbox/polylabel#11]
In https://github.com/mapbox/polylabel/blob/master/index.js#L95, we iterate each segments to calculate distance from point to segment.

Support we have a polygon with 4 nodes as fellows. We should see that point 0 and 4 are identical. So I think the calculation of point to segment 4-0 is unnecessary.

![image](https://cloud.githubusercontent.com/assets/1522494/18821652/a564f44c-83da-11e6-824e-53c5ec9d5c81.png)

However, for compatible reason, it is appropriate to keep this  redundant calculation, in case of non-closed polygons. Am I correct?

**Comment by mourner** [comment]
Yes, this is to make sure we handle non-closed polygons too. Also, in practice this does not have a noticeable performance overhead.
