### ISSUE TITLE
Edge Case

### ISSUE THREAD

**Issue by motjokk** [mapbox/polylabel#110]
Regarding Korridor. Narrow canyon!
![image](https://github.com/mapbox/polylabel/assets/33512457/4dcd7b1e-af2c-47b0-b3d6-48ee1ae5325d)

**Comment by mourner** [comment]
Can you share more details? What result do you expect, and what do you get instead? Can you share the exact input you're giving to polylabel?

**Comment by motjokk** [comment]
It seems I have made a mistake. The space does not have a room name. Thank you for following up!
