### ISSUE TITLE
default full screen map in blazor

### ISSUE THREAD

**Issue by MahdiElahi** [mapbox/polylabel#111]
i want when page loaded map is default is full screen 
i use this code 

`    map.toggleFullscreen();`

but when navigate from pages this code is worked but when in map page user refresh page it's not worked and show this error 

**Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture. toggleFullscreen @ leaflet.fullscreen.min.js:1**

**Comment by mourner** [comment]
1. You've submitted an issue to the wrong repo.
2. I don't think there's a solution. Browsers don't allow initiating full screen on page load, it has to happen on a user gesture such as a click, no way for us to do anything about it.
