### ISSUE TITLE
Bug repot: calculated center is out of polygon

### ISSUE THREAD

**Issue by skywalkerlw** [mapbox/polylabel#112]
Here is an example

150.9352184,-33.880303
150.9356689,-33.8801071
150.9352372,-33.8802915
150.9352184,-33.880303

![image](https://github.com/mapbox/polylabel/assets/2090084/844efbe5-364a-4f0f-be6f-5b36c4efd58f)

**Comment by mourner** [comment]
What precision value do use use when calling `polylabel`?
