### ISSUE TITLE
Infinite loop while trying to find most promising cell from the queue

### ISSUE THREAD

**Issue by demkalkov** [mapbox/polylabel#15]
In my case I've used us states map and have been trying to find the center of the states, but faced an infinite loop for some states because [getCentroidCell]( https://github.com/mapbox/polylabel/blob/master/index.js#L37) used to return structure like
`
{
 x: NaN,
 y: NaN,
 d: NaN
 .
 .
 .
}
`

so when it tried to compare the numbers [later](https://github.com/mapbox/polylabel/blob/master/index.js#L56), it had always the negative result

**Comment by TWiStErRob** [comment]
Is everything a Number in your passed in `polygon`? String coordinates won't work.

**Comment by demkalkov** [comment]
The polygon's value is `[[0,0]]`. 
Seems like for the current scale this states are too small. So in this case the area will be equal to zero, and there will be division by zero

**Comment by TWiStErRob** [comment]
Ah, yes, 0/0 is NaN, but N/0 is Infinity.

**Comment by mourner** [comment]
Agreed. We should probably bail out early in case of zero-area polygons.
