### ISSUE TITLE
polylabel as a command line utility

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/polylabel#17]
@mourner I wanted a command line utility to wrap up this library so I put together one at https://github.com/andrewharvey/geojson-polygon-labels

Not sure if you're interested in including a utility within the `polylabel` repo or a link in the README, or if not that's fine. Anyway just thought I would let you know.

**Comment by mourner** [comment]
I'm fine with this living as a separate repo. Thanks for making it :) I'll welcome a PR with a Readme notice.
