### ISSUE TITLE
Ported to R?

### ISSUE THREAD

**Issue by briatte** [mapbox/polylabel#23]
Do you know if this algorithm been ported to R, and if not, if there are plans to do so?

Since the code is C++, it should be relatively easy to do – although I admit having no clear idea of how to do it.

**Comment by mourner** [comment]
I'm not aware of any plans to port to R, but you're welcome to do this. I'll be happy to add a note with a link in the readme once it is done.

**Comment by jolars** [comment]
I have created an R package for polylabel. It is available at <https://CRAN.R-project.org/package=polylabelr>. Would you please consider linking to it @mourner ?

**Comment by mourner** [comment]
@jolars sure — would you be open to a PR?

**Comment by jolars** [comment]
Sure! https://github.com/mapbox/polylabel/pull/48
