### ISSUE TITLE
Handling multi-ring polygons

### ISSUE THREAD

**Issue by spoilsportmotors** [mapbox/polylabel#27]
I don't think this handles - or intends to handle - polygons with multiple rings. Typically, polygon rings with counter-clockwise winding are 'solid' and clockwise windings represent 'holes'.

Any thoughts on the level of effort to extend this library to account for polygons with one or more holes?

**Comment by mourner** [comment]
It fully supports polygons with holes already, exactly how you describe. You can even see it in action on the illustration in the readme.

**Comment by spoilsportmotors** [comment]
Thanks - let me go back and look at my data - I thought it was multi-part polys (ESRI geodatabase), but maybe they're malformed.
