### ISSUE TITLE
Typings not working.

### ISSUE THREAD

**Issue by Zahma** [mapbox/polylabel#31]
I have tried to work with the typings you provided but its not working. 

So I tried to put some modificationsand I ended up with the following code:

````
declare namespace polylabel {
/**
 * Polylabel returns the pole of inaccessibility coordinate in [x, y] format.
 * 
 * @name polylabel
 * @function
 * @param {Array<number>} polygon - Given polygon coordinates in GeoJSON-like format
 * @param {number} precision - Precision (1.0 by default)
 * @param {boolean} debug - Debugging for Console 
 * @return {Array<number>}
 * @example
 * var p = polylabel(polygon, 1.0);
 */
function polylabel(polygon: number[][][], precision?: number, debug?: boolean): number[];
}

declare module "polylabel" {
	export = polylabel.polylabel;
}
````

Still I'm getting the following error:

> cannot get a expression whose type lacks a call signature

**Comment by mourner** [comment]
This repo does not provide TypeScript definitions. You should report this to the author on a corresponding repo, not here. @DenisCarriere perhaps?

**Comment by DenisCarriere** [comment]
@Zahma I've pushed an update to the Typescript definition file (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19869), if there are any updates on the TypeScript definitions, post them on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) or submit a PR with a fix.

If you define your own typings, you can use the following:

```ts
declare function polylabel(polygon: number[][][], precision?: number, debug?: boolean): number[];
declare namespace polylabel {}
export default polylabel;
```

**Comment by DenisCarriere** [comment]
@Zahma Another thing to note, how are you importing the polylabel module, the current Type Definition does work using the following:

```ts
import * as polylabel from 'polylabel';
console.log(polylabel);
//={ [Function: polylabel] default: [Circular] }
```
