### ISSUE TITLE
Counterintuitive Pole Placement

### ISSUE THREAD

**Issue by stonetip** [mapbox/polylabel#32]
I may misunderstand the way this algorithm works. And from reading the description, it is an impressive bit of work. However, this is just one of several examples where the output is unexpected:

![image](https://user-images.githubusercontent.com/3766798/30626687-ae74893a-9d88-11e7-9c92-8a5ffeb5631b.png)

[weyer1.json.txt](https://github.com/mapbox/polylabel/files/1316590/weyer1.json.txt)

**Comment by talaj** [comment]
If I'm counting correctly there are 10 interior rings in the json, but the image shows more than 10 holes, so the polygon cannot be valid. The algorithm cannot work with invalid polygons. Please correct me if I'm wrong.

**Comment by stonetip** [comment]
I checked a simplified version of the feature for validity in both QGIS and ArcGIS and it seems fine. I also tested it as geoJSON in geoJSONLint. The label point still ended up in the same place. I even temporarily removed all the actual rings and that resulted in an even less likely point. Even with a simpler, definitely single polygonic shape, the results aren't as expected (which I've indicated by manually placing the encircled red point):
![image](https://user-images.githubusercontent.com/3766798/30944541-d13e392e-a3b5-11e7-8237-bfb289b165d0.png)

The attached is the verified and tested file for the original polygon:
[weyer1_S2.json.txt](https://github.com/mapbox/polylabel/files/1339107/weyer1_S2.json.txt)

**Comment by talaj** [comment]
So I've got that position with precision set to `0.01`:
![interior-point-3-512-512-1 0-agg](https://user-images.githubusercontent.com/1950911/30988818-da97f80c-a49b-11e7-8f67-e1866c24cfbf.png)

**Comment by stonetip** [comment]
You know, I've got to go back and look at my code. I'm thinking I either set the precision too coarse or left it out altogether (if that's possible). Because, judging by the image from @talaj above that placement is perfect.

**Comment by mourner** [comment]
I assume this was just a badly picked precision, right?

**Comment by stonetip** [comment]
That was the case. Thanks.
