### ISSUE TITLE
Python wrapper bug

### ISSUE THREAD

**Issue by drewleonard** [mapbox/polylabel#41]
Opening an issue to inform that `polylabel()` from the [linked Python implementation of this library](https://github.com/Twista/python-polylabel) fails when polygons are sufficiently small. (This JavaScript implementation handles this edge case already). I have patched the issue locally and would like to contribute the code, but since the library is from a third-party and this official repository references it, I'm mentioning the issue here.

**Comment by mourner** [comment]
Thanks! You should report the issue in the corresponding port repo though — opening one here isn't necessary.

**Comment by drewleonard** [comment]
Okay will do and thank you! Sorry for the trouble—just wanted to make sure you knew.
