### ISSUE TITLE
What kind of file format does polylabel accept?

### ISSUE THREAD

**Issue by gabrielmoncea** [mapbox/polylabel#43]
I tried with geojson and json. But it seems that content of the file must be specific. Can you please add in documentation what kind of file format does it accept and also, how should the content format be?

**Comment by mourner** [comment]
GeoJSON polygon format is an array of rings, where each ring is an array of `[x, y]` pairs.

**Comment by msageryd** [comment]
@mourner Yes, of course. Sorry for neglecting that.

Updated example for @gabrielmoncea: `const p = polylabel([[[1,1],[1,2],[2,2],[2,1]]], 1.0)`  (one ring)
