### ISSUE TITLE
Using lat/lng coordinates in lieu of GeoJSON format

### ISSUE THREAD

**Issue by mesh-newbie** [mapbox/polylabel#57]
Hi,
Your algorithm looks great :-), but was wondering if I could use it using traditional google maps lat/lng?
Perhaps converting lat/lng to points.. would that work?
https://developers.google.com/maps/documentation/javascript/reference/image-overlay#Projection.fromLatLngToPoint

Thanks

**Comment by mourner** [comment]
Yes. And then convert the result back to `LatLng`.
