### ISSUE TITLE
Incorrect decision of best solution

### ISSUE THREAD

**Issue by serbod** [mapbox/polylabel#68]
![image](https://user-images.githubusercontent.com/11455997/93608768-b0550900-f9d3-11ea-86f1-2e47f3bcd74b.png)

Building at (53.89824, 27.56131)

Upper cell got center point very close to polygon line.

```
        // do not drill down further if there's no chance of a better solution
        if (cell.max - bestCell.d <= precision) continue;
``` 
.. and filtered out by precision

**Comment by serbod** [comment]
I using this algorythm on pixel coordinates with precision of 1 pixel.

**Comment by mourner** [comment]
@serbod if so, can you please provide the full test case, with coordinates?

The algorithm should work correctly in the case above, since `cell.max` will be high enough with the big cell not to stop.

**Comment by Komzpa** [comment]
Context: https://t.me/bygis/18840
Issue is observed in Pascal port of library and looks like buggy/nonexistent priority queue implementation.

**Comment by serbod** [comment]
Yes, problem is exactly with improper queue sorting in my implementation. Thanks for help and sorry for disturbance!
![image](https://user-images.githubusercontent.com/11455997/93742355-a19a6c00-fbf6-11ea-828e-0605a8aad2ec.png)
