### ISSUE TITLE
Use ES-modules instead of CommonJS or AMD

### ISSUE THREAD

**Issue by dennisheer** [mapbox/polylabel#74]
Compiling with Angular CLI version greater than 10 results in a warning by the Angular compiler. This is caused by the usage of CommonJS or AMD dependencies within this package or its dependencies.

<img width="675" alt="Screenshot 2020-10-21 at 16 04 50" src="https://user-images.githubusercontent.com/15670613/96731189-460afc00-13b7-11eb-81d1-242a9a7f4cb4.png">

Can you provide a version of your module only using ES-modules? I'm currently using version `1.1.0` of `polylabel`.

**Comment by mourner** [comment]
Done in https://github.com/mapbox/polylabel/commit/93787d50a6f6a492beac705584d39f59ca112aa0 (will be released in v2.0.0 shortly)
