### ISSUE TITLE
To get top N 'Best point' in the  polygon and have a min-distance between each other.

### ISSUE THREAD

**Issue by f236964158** [mapbox/polylabel#75]
Hi 
i have this question when i trying to place more label in the poly.how to To get top N 'Best point' in the  polygon and have a min-distance between each other.have any suggestion?
![1](https://user-images.githubusercontent.com/26860825/97554757-2fe1e900-1a12-11eb-8d48-4f0378b4a847.jpg)

regards

**Comment by mourner** [comment]
I'm afraid this is out of scope for this library — it is very hard to mathematically define what "N best points" means specifically in context of the polylabel algorithm. The next "best" point after the first one would be one pixel away from it. One workaround may be to simply split big polygons into multiple parts (e.g. slicing vertically or horizontally), but I don't have any good suggestions beyond that.
