### ISSUE TITLE
Result point is out of polygon

### ISSUE THREAD

**Issue by inaferando** [mapbox/polylabel#78]
I'm trying to find the label point for Lago di Livigno lake in Italy. The result point is out of polygon bounds. See the source polygon and the picture. The coordinates of the result point are:

10.179204834796153,
46.593747060598524

![livigno](https://user-images.githubusercontent.com/1243824/103078148-51aab700-45e2-11eb-9ed2-554050723a92.png)
[livigno.geojson.txt](https://github.com/mapbox/polylabel/files/5738992/livigno.geojson.txt)

**Comment by mourner** [comment]
You're likely not passing small enough `tolerance` value. Try something like `0.00001`.
