### ISSUE TITLE
matlab to javascript GeoJSON-like format, and back

### ISSUE THREAD

**Issue by octlie** [mapbox/polylabel#79]
Dear All, 

I have a 2D polygon defined by (x,y) coordinates array in a .mat file, where coordinates are corresponding to a hAxes coordinate system/handle in a matlab figure. I would like to know how I can convert it to a GeoJSON-like format input for polylabel, also how to translate the output back to the hAxes coordinate system. An additional bonus would be an example of how to call polylabel from matlab, thank you very much, Octavian

**Comment by mourner** [comment]
Hi Octavian, I'm not familiar with the matlab format, and this is not the place for asking questions anyway (it's for reporting issues with the library) — please try asking on StackOverflow instead.
