### ISSUE TITLE
Open GitHub discussions for this project?

### ISSUE THREAD

**Issue by hollasch** [mapbox/polylabel#80]
[GitHub Discussions](https://docs.github.com/en/discussions/quickstart#welcoming-contributions-to-your-discussions) is a new GitHub feature that provides a project-focused forum for conversations related to the project. See the [discussions page for the _Ray Tracing in One Weekend_ project](https://github.com/RayTracing/raytracing.github.io/discussions) as an example.

I think this would be a good fit for this project, as there are many useful variants to this algorithm, but it seems this project is not about ongoing support and optimization -- instead, it appears to be provided as a (very) useful addendum to the PolyLabel algorithm and article. Given that, open-ended discussions may prove to be more useful in the long run than opening issues against the project, and don't require or suggest response from the project maintainers.

Would you be willing to host project-related discussions for this repo? If so, you just need to go to the project settings tab and enable discussions. Thanks!

**Comment by mourner** [comment]
Opened, let's try it out 👍
