### ISSUE TITLE
Trivially reject subcells before adding them to the priority queue

### ISSUE THREAD

**Issue by hollasch** [mapbox/polylabel#82]
Frequently a newly-generated quadrant cell cannot possibly beat the current best cell. In this case, it's wasted work to add it to the priority queue just so we can discard it later, particularly since the priority queue needs to find the correct location to insert the new cell.

In my test cases, a pure square polygon yielded zero savings. All other test cases were able to immediately skip adding between 10% and 72% of the newly-generated cells. The maximium queue size shrunk down to 87%-4.5% of the original queue size.

To accomplish this in the JavaScript version, you'd change
```
cellQueue.push(new Cell(cell.x - h, cell.y - h, h, polygon));
cellQueue.push(new Cell(cell.x + h, cell.y - h, h, polygon));
cellQueue.push(new Cell(cell.x - h, cell.y + h, h, polygon));
cellQueue.push(new Cell(cell.x + h, cell.y + h, h, polygon));
```

to something like this:

```
newCell0 = new Cell(cell.x - h, cell.y - h, h, polygon));
newCell1 = new Cell(cell.x + h, cell.y - h, h, polygon));
newCell2 = new Cell(cell.x - h, cell.y + h, h, polygon));
newCell3 = new Cell(cell.x + h, cell.y + h, h, polygon));

if (newcell0.max > bestCell.d) cellQueue.push(newCell0);
if (newcell1.max > bestCell.d) cellQueue.push(newCell1);
if (newcell2.max > bestCell.d) cellQueue.push(newCell2);
if (newcell3.max > bestCell.d) cellQueue.push(newCell3);
```

Verified with my test cases.

**Comment by mourner** [comment]
This is a brilliant catch! I tried benchmarking it locally on some fixtures, and while it doesn't show any noticeable performance improvement, the queue does grow much less, so I'd expect it would still be a win in the end because of less GC on the queue array.
