### ISSUE TITLE
How to import using ES6 syntax?

### ISSUE THREAD

**Issue by DenisCarriere** [mapbox/polylabel#9]
Having issues wrapping my head around importing this module using a ES6 syntax.

Can you elaborate on how  to import this module? 

Which one of these would be ES6 valid and still functional?

```javascript
const polylabel = require('polylabel')
import polylabel from 'polylabel'
import { polylabel } from 'polylabel'
import * as polylabel from 'polylabel'
```

**Comment by mourner** [comment]
-> #10
