### ISSUE TITLE
npm has not the newest release

### ISSUE THREAD

**Issue by Falke-Design** [mapbox/polylabel#95]
![grafik](https://user-images.githubusercontent.com/19800037/169647645-3d8922e4-2835-4bb8-b26e-bde23da26a23.png)

**Comment by mourner** [comment]
It's just `polylabel`, without namespaces. I guess I need to mark `@mapbox/polylabel` as deprecated.

**Comment by Falke-Design** [comment]
Ou ok thanks 😄 

Only as hint, Github Release and npm doesn't have the same latest release.
![grafik](https://user-images.githubusercontent.com/19800037/169647980-4703c9e9-6bcf-4b62-a1d3-145d644889c0.png)

![grafik](https://user-images.githubusercontent.com/19800037/169647987-f8df8fb0-f180-4445-bc22-767160b0077b.png)
