### ISSUE TITLE
The algorithm is not guaranteed to find a point that lies inside the polygon

### ISSUE THREAD

**Issue by alex-petkov** [mapbox/polylabel#97]
If all initial cells' centers lie outside the polygon and the precision is large enough for `cell.max - bestCell.d <= precision` to return `true`, the algorithm will return a point that lies outside the polygon, as it will not drill down into any more cells. It may be desirable to always return a point that lies inside the polygon, regardless of the `precision` parameter, as the dimensions of the polygons may not be known in advance to provide an adequate `precision` value. This can easily be fixed by preventing drill down only if the best cell is inside the polygon:
```cpp
// do not drill down further if there's no chance of a better solution
// but only if our best cell's center is inside the polygon
if ((cell.max - bestCell.d <= precision) && (bestCell.d > 0))
```
A more efficient approach would be to monitor every potential cell's `.d` value and set a flag to true if one that is positive is found. This would reduce the amount of cells with low potential in the queue but to implement it we need to introduce an extra variable in the algorithm.

**Comment by pbeeson** [comment]
The trivial solution for this is to change the code so that if the best_cell has negative center distance (outside the polygon), just use any polygon vertex as the best cell instead.  This guarantees that if the precision is already high, at least you get a point on the polygon.
