### ISSUE TITLE
How to install latest version with NPM?

### ISSUE THREAD

**Issue by plarner30** [mapbox/polylabel#99]
package.json:

`"@mapbox/polylabel": "^1.0.2",` works
`"@mapbox/polylabel": "^1.0.4",` No matching version found for @mapbox/polylabel@^1.0.4
`"@mapbox/polylabel": "^1.1.0",` No matching version found for @mapbox/polylabel@^v1.1.0

**Comment by mourner** [comment]
It's not namespaced:

https://github.com/mapbox/polylabel/blob/4da88d5eff01b7d98a8b2876d7847ba334144013/package.json#L2

**Comment by plarner30** [comment]
thanks
